// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Application
{
	public class GameEndState:IGameState
	{
		private readonly GameManager _manager;
		public GameEndState (GameManager manager)
		{
			this._manager = manager;
			Debug.Log ("Enter End");
		}

		public override void Update()
		{
			Debug.Log("In End");
		}

		public override void SwitchNext()
		{

		}
	}
}

