// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace Application
{
	public class GameStartState:IGameState
	{
		private readonly GameManager _manager;
		public GameStartState (GameManager manager)
		{
			this._manager = manager;
			Debug.Log ("Enter start");
		}

		public override void Update()
		{
			if(Input.GetKeyDown(KeyCode.A))
			{
				SwitchNext();
			}
			//Debug.Log ("In Start");
		}

		public override void SwitchNext()
		{
			_manager._CurrentState = new GameRunState (_manager);
		}
	}
}

